spring:
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
#    url: jdbc:h2:file:/Users/m.kharkov/sirius-test
    url: jdbc:h2:mem:sirius-test
    username: test
    password: test
    driver-class-name: org.h2.Driver
